# Softmax Regression

In [2]:
import tensorflow as tf

In [20]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3]) #label 갯수
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes], name = 'weight'))
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print('cost: ')
    for step in range(2001):
        sess.run(optimizer, feed_dict = {X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict = {X: x_data, Y: y_data}))
        
    print('--------------------\na: ')
    a = sess.run(hypothesis, feed_dict={X:[[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))
    
    print('--------------------\nb: ')
    b = sess.run(hypothesis, feed_dict={X:[[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))
    
    print('--------------------\nc: ')
    c = sess.run(hypothesis, feed_dict={X:[[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))
    
    print('--------------------\nall: ')
    all = sess.run(hypothesis, feed_dict={X:[[1, 11, 7, 9], [1, 3, 4, 3], [1 ,1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

cost: 
0 4.257083
200 0.63245267
400 0.51723605
600 0.42029616
800 0.32812208
1000 0.25334054
1200 0.22778259
1400 0.20732868
1600 0.19014195
1800 0.17549449
2000 0.16286616
--------------------
a: 
[[3.4367338e-02 9.6562487e-01 7.8478870e-06]] [1]
--------------------
b: 
[[0.66518855 0.31483546 0.01997603]] [0]
--------------------
c: 
[[1.2554878e-08 3.6922650e-04 9.9963069e-01]] [2]
--------------------
all: 
[[3.4367274e-02 9.6562493e-01 7.8478952e-06]
 [6.6518855e-01 3.1483537e-01 1.9976020e-02]
 [1.2554878e-08 3.6922650e-04 9.9963069e-01]] [1 0 2]
