In [3]:
import tensorflow as tf

x_data = [73., 80., 75.],[93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]
y_data = [152.], [185.], [180.], [196.], [142.]

X = tf.placeholder(tf.float32, shape = [None,3])
Y = tf.placeholder(tf.float32, shape = [None,1])

W = tf.Variable(tf.random_normal([3,1]), name = 'Weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train], feed_dict={X : x_data, Y: y_data})
    if(step % 10 == 0):
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  16621.543 
Prediction:
 [[36.840008]
 [47.426   ]
 [45.2649  ]
 [47.689754]
 [38.222324]]
10 Cost:  0.74090785 
Prediction:
 [[150.88852]
 [184.50049]
 [180.32843]
 [194.77058]
 [142.7748 ]]
20 Cost:  0.5874578 
Prediction:
 [[151.23532]
 [184.91402]
 [180.7376 ]
 [195.21617]
 [143.08937]]
30 Cost:  0.5861783 
Prediction:
 [[151.23808]
 [184.91408]
 [180.73935]
 [195.21811]
 [143.08858]]
40 Cost:  0.5848998 
Prediction:
 [[151.23982]
 [184.91287]
 [180.73984]
 [195.21866]
 [143.08682]]
50 Cost:  0.58363503 
Prediction:
 [[151.24153]
 [184.91167]
 [180.74036]
 [195.21925]
 [143.08508]]
60 Cost:  0.5823668 
Prediction:
 [[151.24324]
 [184.91048]
 [180.74084]
 [195.21982]
 [143.08333]]
70 Cost:  0.5811084 
Prediction:
 [[151.24496]
 [184.90929]
 [180.74135]
 [195.22038]
 [143.08159]]
80 Cost:  0.5798585 
Prediction:
 [[151.24667]
 [184.90808]
 [180.74184]
 [195.22093]
 [143.07985]]
90 Cost:  0.5786103 
Prediction:
 [[151.24837]
 [184.9069 ]
 [180.74234]
 [195.22151]
 [143.07811]]

980 Cost:  0.4893562 
Prediction:
 [[151.38177]
 [184.81358]
 [180.7808 ]
 [195.26773]
 [142.94019]]
990 Cost:  0.4885568 
Prediction:
 [[151.3831 ]
 [184.81267]
 [180.78119]
 [195.26822]
 [142.93881]]
1000 Cost:  0.48777825 
Prediction:
 [[151.3844 ]
 [184.81174]
 [180.78157]
 [195.26869]
 [142.93745]]
1010 Cost:  0.4869783 
Prediction:
 [[151.3857 ]
 [184.81084]
 [180.78192]
 [195.26917]
 [142.93607]]
1020 Cost:  0.48618802 
Prediction:
 [[151.38701]
 [184.8099 ]
 [180.78229]
 [195.26962]
 [142.93468]]
1030 Cost:  0.48541397 
Prediction:
 [[151.38832]
 [184.80902]
 [180.78268]
 [195.27011]
 [142.93333]]
1040 Cost:  0.48464075 
Prediction:
 [[151.3896 ]
 [184.80809]
 [180.78305]
 [195.27057]
 [142.93196]]
1050 Cost:  0.4838646 
Prediction:
 [[151.3909 ]
 [184.8072 ]
 [180.78342]
 [195.27106]
 [142.93062]]
1060 Cost:  0.4830951 
Prediction:
 [[151.39218]
 [184.80627]
 [180.78378]
 [195.27151]
 [142.92924]]
1070 Cost:  0.48232517 
Prediction:
 [[151.39346]
 [184.80539]
 [180.78415]
 [19

1940 Cost:  0.42791194 
Prediction:
 [[151.49202]
 [184.73604]
 [180.81206]
 [195.30972]
 [142.82214]]
1950 Cost:  0.427406 
Prediction:
 [[151.49301]
 [184.73537]
 [180.81235]
 [195.31013]
 [142.82106]]
1960 Cost:  0.42690533 
Prediction:
 [[151.494  ]
 [184.73465]
 [180.81262]
 [195.31053]
 [142.81998]]
1970 Cost:  0.42640227 
Prediction:
 [[151.49498]
 [184.73395]
 [180.8129 ]
 [195.31093]
 [142.81888]]
1980 Cost:  0.4259048 
Prediction:
 [[151.49597]
 [184.73328]
 [180.81319]
 [195.31134]
 [142.81781]]
1990 Cost:  0.42540684 
Prediction:
 [[151.49696]
 [184.73256]
 [180.81345]
 [195.31172]
 [142.81673]]
2000 Cost:  0.42491975 
Prediction:
 [[151.49794]
 [184.73187]
 [180.81372]
 [195.3121 ]
 [142.81566]]
