In [4]:
import tensorflow as tf

In [7]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [8]:
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [9]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,3])

In [10]:
W = tf.Variable(tf.random_normal([3,3]), name = 'weight')
b = tf.Variable(tf.random_normal([3]), name = 'bias')

In [11]:
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [12]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [13]:
prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction,tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

W0707 14:40:51.004258  7824 deprecation.py:323] From <ipython-input-13-6dd4ffb993a4>:1: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.math.argmax` instead


In [18]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(201):
    cost_val, W_val,_ = sess.run([cost, W, optimizer],
                        feed_dict={X:x_data,Y:y_data})
    print(step, cost_val, W_val)

0 4.179285 [[ 1.1125448  -0.4367595  -0.36351532]
 [-0.20935646  0.3136332  -0.06942008]
 [ 0.52199984  0.5509812  -1.0614928 ]]
1 3.1273558 [[ 1.084089   -0.44563887 -0.32618028]
 [-0.23308264  0.23772028  0.03021904]
 [ 0.48417807  0.50150234 -0.97419214]]
2 2.811853 [[ 1.0508479  -0.44960493 -0.28897303]
 [-0.2831986   0.18849577  0.12955952]
 [ 0.42109704  0.47745976 -0.88706857]]
3 2.4992385 [[ 1.0225176  -0.45821375 -0.25203392]
 [-0.3093202   0.11594018  0.2282367 ]
 [ 0.38207874  0.42976958 -0.8003601 ]]
4 2.1914082 [[ 0.9903668  -0.46250552 -0.21559136]
 [-0.3574378   0.06678848  0.32550597]
 [ 0.32184574  0.4042538  -0.7146113 ]]
5 1.8948239 [[ 0.9631596  -0.47057292 -0.18031678]
 [-0.38264513 -0.00129576  0.41879758]
 [ 0.2842442   0.35904405 -0.6318    ]]
6 1.62896 [[ 0.93378866 -0.4735811  -0.14793766]
 [-0.42263144 -0.04154107  0.4990292 ]
 [ 0.23147433  0.3393331  -0.55931914]]
7 1.4475722 [[ 0.91160375 -0.47691566 -0.12241816]
 [-0.42921886 -0.07974854  0.5438241 ]
 [ 0

In [19]:
print("Prediction:", sess.run(prediction, feed_dict={X:x_test}))

Prediction: [2 2 2]


In [20]:
print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

Accuracy: 1.0
