## Using Matrix Multiply

In [1]:
import tensorflow as tf

In [2]:
x_data = [[73., 80., 75.], [93., 88., 93.],
          [89., 91., 90.], [96., 98., 100.],[73., 66., 70.]]
y_data = [[152.], [185.],[180.],[196.],[142.]]

In [3]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [4]:
W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bais')

In [5]:
hypothesis = tf.matmul(X,W) + b

In [6]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)

In [8]:
train = optimizer.minimize(cost)

In [9]:
sess = tf.Session()

In [10]:
sess.run(tf.global_variables_initializer())

In [13]:
for i in range(100000):
    cost_val, hy_val,_ = sess.run([cost,hypothesis,train],
                        feed_dict={X:x_data, Y:y_data})
    if i % 100 == 0:
        print(i, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  25.281845 
Prediction:
 [[155.93828]
 [181.16327]
 [181.5996 ]
 [200.95917]
 [133.69177]]
100 Cost:  24.193613 
Prediction:
 [[155.77057]
 [181.27931]
 [181.54956]
 [200.91241]
 [133.85295]]
200 Cost:  23.161572 
Prediction:
 [[155.60747]
 [181.3922 ]
 [181.50095]
 [200.8667 ]
 [134.01   ]]
300 Cost:  22.18293 
Prediction:
 [[155.44885]
 [181.50198]
 [181.45369]
 [200.82199]
 [134.16296]]
400 Cost:  21.254711 
Prediction:
 [[155.29459]
 [181.60881]
 [181.40776]
 [200.77827]
 [134.312  ]]
500 Cost:  20.374409 
Prediction:
 [[155.14455]
 [181.7127 ]
 [181.36316]
 [200.73553]
 [134.45718]]
600 Cost:  19.539316 
Prediction:
 [[154.99866]
 [181.8138 ]
 [181.31978]
 [200.69371]
 [134.59865]]
700 Cost:  18.747288 
Prediction:
 [[154.85678]
 [181.91211]
 [181.27765]
 [200.65283]
 [134.73647]]
800 Cost:  17.995922 
Prediction:
 [[154.7188 ]
 [182.00774]
 [181.23671]
 [200.61282]
 [134.87073]]
900 Cost:  17.28313 
Prediction:
 [[154.58466]
 [182.10077]
 [181.19696]
 [200.5737 ]
 [135.00

8100 Cost:  3.7608733 
Prediction:
 [[150.55917]
 [184.92944]
 [180.05135]
 [199.06221]
 [139.29008]]
8200 Cost:  3.731659 
Prediction:
 [[150.54393]
 [184.94078]
 [180.04779]
 [199.05098]
 [139.31227]]
8300 Cost:  3.7032325 
Prediction:
 [[150.5292 ]
 [184.95178]
 [180.04439]
 [199.03989]
 [139.33397]]
8400 Cost:  3.6755338 
Prediction:
 [[150.51494]
 [184.96239]
 [180.04112]
 [199.0289 ]
 [139.35521]]
8500 Cost:  3.6485276 
Prediction:
 [[150.50117]
 [184.97272]
 [180.03801]
 [199.01805]
 [139.376  ]]
8600 Cost:  3.6222146 
Prediction:
 [[150.48784]
 [184.9827 ]
 [180.03502]
 [199.00731]
 [139.39635]]
8700 Cost:  3.5965168 
Prediction:
 [[150.475  ]
 [184.99239]
 [180.0322 ]
 [198.99672]
 [139.41629]]
8800 Cost:  3.571447 
Prediction:
 [[150.46257]
 [185.00174]
 [180.02948]
 [198.9862 ]
 [139.43578]]
8900 Cost:  3.5469537 
Prediction:
 [[150.45058]
 [185.01083]
 [180.0269 ]
 [198.97585]
 [139.4549 ]]
9000 Cost:  3.5229752 
Prediction:
 [[150.43903]
 [185.01965]
 [180.02446]
 [198.965

16200 Cost:  2.4390264 
Prediction:
 [[150.21274]
 [185.23141]
 [180.02716]
 [198.40723]
 [140.22467]]
16300 Cost:  2.4280393 
Prediction:
 [[150.21387]
 [185.23138]
 [180.02843]
 [198.40102]
 [140.23062]]
16400 Cost:  2.417133 
Prediction:
 [[150.21504]
 [185.23131]
 [180.02968]
 [198.39485]
 [140.23651]]
16500 Cost:  2.4062743 
Prediction:
 [[150.21626]
 [185.23119]
 [180.03096]
 [198.38869]
 [140.24232]]
16600 Cost:  2.3954844 
Prediction:
 [[150.21753]
 [185.23102]
 [180.03226]
 [198.38257]
 [140.2481 ]]
16700 Cost:  2.384773 
Prediction:
 [[150.21883]
 [185.23083]
 [180.03357]
 [198.37648]
 [140.2538 ]]
16800 Cost:  2.3740978 
Prediction:
 [[150.22017]
 [185.23062]
 [180.03488]
 [198.37039]
 [140.25945]]
16900 Cost:  2.3634756 
Prediction:
 [[150.22159]
 [185.2304 ]
 [180.03624]
 [198.36436]
 [140.26506]]
17000 Cost:  2.3528888 
Prediction:
 [[150.22302]
 [185.2301 ]
 [180.03755]
 [198.3583 ]
 [140.2706 ]]
17100 Cost:  2.3424363 
Prediction:
 [[150.22449]
 [185.2298 ]
 [180.0389 ]

24400 Cost:  1.7032261 
Prediction:
 [[150.38411]
 [185.16753]
 [180.14769]
 [197.96501]
 [140.58795]]
24500 Cost:  1.6959484 
Prediction:
 [[150.38655]
 [185.16644]
 [180.14919]
 [197.96025]
 [140.59146]]
24600 Cost:  1.6887287 
Prediction:
 [[150.38899]
 [185.16536]
 [180.15067]
 [197.95552]
 [140.59494]]
24700 Cost:  1.6815403 
Prediction:
 [[150.39143]
 [185.16428]
 [180.15218]
 [197.9508 ]
 [140.59842]]
24800 Cost:  1.6743768 
Prediction:
 [[150.39388]
 [185.1632 ]
 [180.15367]
 [197.94609]
 [140.60188]]
24900 Cost:  1.6672583 
Prediction:
 [[150.3963 ]
 [185.1621 ]
 [180.15514]
 [197.94139]
 [140.60533]]
25000 Cost:  1.6601712 
Prediction:
 [[150.39874]
 [185.16101]
 [180.15665]
 [197.9367 ]
 [140.60876]]
25100 Cost:  1.6531315 
Prediction:
 [[150.40118]
 [185.15994]
 [180.15811]
 [197.93205]
 [140.61218]]
25200 Cost:  1.6461134 
Prediction:
 [[150.40361]
 [185.15883]
 [180.15959]
 [197.92738]
 [140.61559]]
25300 Cost:  1.639129 
Prediction:
 [[150.40605]
 [185.15775]
 [180.16109

32500 Cost:  1.215834 
Prediction:
 [[150.57317]
 [185.08134]
 [180.2607 ]
 [197.61769]
 [140.83733]]
32600 Cost:  1.2109371 
Prediction:
 [[150.57535]
 [185.08034]
 [180.26198]
 [197.61385]
 [140.84006]]
32700 Cost:  1.2060661 
Prediction:
 [[150.57748]
 [185.07932]
 [180.26323]
 [197.60995]
 [140.84274]]
32800 Cost:  1.2012129 
Prediction:
 [[150.57967]
 [185.07835]
 [180.26454]
 [197.60616]
 [140.8455 ]]
32900 Cost:  1.1963866 
Prediction:
 [[150.58182]
 [185.07735]
 [180.2658 ]
 [197.60231]
 [140.84819]]
33000 Cost:  1.1915716 
Prediction:
 [[150.58397]
 [185.07632]
 [180.26704]
 [197.59846]
 [140.85088]]
33100 Cost:  1.186795 
Prediction:
 [[150.58612]
 [185.07535]
 [180.26833]
 [197.59467]
 [140.85358]]
33200 Cost:  1.1820345 
Prediction:
 [[150.58826]
 [185.07437]
 [180.26959]
 [197.59085]
 [140.85626]]
33300 Cost:  1.1772888 
Prediction:
 [[150.59041]
 [185.07338]
 [180.27086]
 [197.58707]
 [140.85896]]
33400 Cost:  1.1725813 
Prediction:
 [[150.59253]
 [185.07239]
 [180.27211]

40600 Cost:  0.88684064 
Prediction:
 [[150.734  ]
 [185.00679]
 [180.35518]
 [197.33359]
 [141.03731]]
40700 Cost:  0.883527 
Prediction:
 [[150.7358 ]
 [185.00594]
 [180.35622]
 [197.33041]
 [141.03954]]
40800 Cost:  0.88023394 
Prediction:
 [[150.7376 ]
 [185.00511]
 [180.35728]
 [197.32726]
 [141.04176]]
40900 Cost:  0.8769558 
Prediction:
 [[150.73938]
 [185.00426]
 [180.35832]
 [197.32408]
 [141.04396]]
41000 Cost:  0.8737003 
Prediction:
 [[150.74117]
 [185.00343]
 [180.35938]
 [197.32095]
 [141.04619]]
41100 Cost:  0.8704542 
Prediction:
 [[150.74295]
 [185.00261]
 [180.36041]
 [197.31781]
 [141.04839]]
41200 Cost:  0.86723375 
Prediction:
 [[150.74472]
 [185.00177]
 [180.36147]
 [197.31468]
 [141.05058]]
41300 Cost:  0.8640113 
Prediction:
 [[150.7465 ]
 [185.00095]
 [180.3625 ]
 [197.31155]
 [141.05278]]
41400 Cost:  0.8608136 
Prediction:
 [[150.74828]
 [185.0001 ]
 [180.36353]
 [197.30843]
 [141.05495]]
41500 Cost:  0.85764045 
Prediction:
 [[150.75005]
 [184.99931]
 [180.3

 [[150.86525]
 [184.94576]
 [180.43204]
 [197.10292]
 [141.19926]]
48700 Cost:  0.66473705 
Prediction:
 [[150.86673]
 [184.94507]
 [180.4329 ]
 [197.10031]
 [141.20108]]
48800 Cost:  0.66249436 
Prediction:
 [[150.86823]
 [184.94437]
 [180.43378]
 [197.0977 ]
 [141.20291]]
48900 Cost:  0.6602794 
Prediction:
 [[150.8697 ]
 [184.9437 ]
 [180.43466]
 [197.09512]
 [141.20474]]
49000 Cost:  0.65806586 
Prediction:
 [[150.87117]
 [184.943  ]
 [180.4355 ]
 [197.09251]
 [141.20654]]
49100 Cost:  0.6558664 
Prediction:
 [[150.87265]
 [184.94232]
 [180.43639]
 [197.08994]
 [141.20836]]
49200 Cost:  0.6536695 
Prediction:
 [[150.87411]
 [184.94164]
 [180.43724]
 [197.08736]
 [141.21019]]
49300 Cost:  0.65148956 
Prediction:
 [[150.87558]
 [184.94095]
 [180.43808]
 [197.08478]
 [141.21198]]
49400 Cost:  0.64931905 
Prediction:
 [[150.87704]
 [184.94028]
 [180.43893]
 [197.08221]
 [141.21378]]
49500 Cost:  0.6471607 
Prediction:
 [[150.8785 ]
 [184.9396 ]
 [180.43979]
 [197.07965]
 [141.21558]]
4

57500 Cost:  0.5043627 
Prediction:
 [[150.98439]
 [184.89037]
 [180.50172]
 [196.89384]
 [141.34605]]
57600 Cost:  0.50290984 
Prediction:
 [[150.98558]
 [184.88982]
 [180.50243]
 [196.89174]
 [141.34752]]
57700 Cost:  0.5014572 
Prediction:
 [[150.98677]
 [184.88925]
 [180.50313]
 [196.88963]
 [141.349  ]]
57800 Cost:  0.500006 
Prediction:
 [[150.98796]
 [184.88869]
 [180.5038 ]
 [196.88753]
 [141.35046]]
57900 Cost:  0.49858063 
Prediction:
 [[150.98914]
 [184.88814]
 [180.5045 ]
 [196.88545]
 [141.35193]]
58000 Cost:  0.49715048 
Prediction:
 [[150.99034]
 [184.88759]
 [180.5052 ]
 [196.88338]
 [141.35338]]
58100 Cost:  0.49572363 
Prediction:
 [[150.99155]
 [184.88705]
 [180.50592]
 [196.88132]
 [141.35486]]
58200 Cost:  0.4943079 
Prediction:
 [[150.9927 ]
 [184.88649]
 [180.50659]
 [196.87923]
 [141.35631]]
58300 Cost:  0.49289948 
Prediction:
 [[150.99388]
 [184.88594]
 [180.50726]
 [196.87717]
 [141.35776]]
58400 Cost:  0.49149457 
Prediction:
 [[150.99506]
 [184.8854 ]
 [180

65500 Cost:  0.40747538 
Prediction:
 [[151.07161]
 [184.84982]
 [180.55269]
 [196.74083]
 [141.45354]]
65600 Cost:  0.40649152 
Prediction:
 [[151.07259]
 [184.84935]
 [180.55325]
 [196.73909]
 [141.45473]]
65700 Cost:  0.40549797 
Prediction:
 [[151.07358]
 [184.84889]
 [180.55382]
 [196.73737]
 [141.45596]]
65800 Cost:  0.4045238 
Prediction:
 [[151.07455]
 [184.84845]
 [180.55441]
 [196.73563]
 [141.45715]]
65900 Cost:  0.40354824 
Prediction:
 [[151.07553]
 [184.84798]
 [180.55498]
 [196.7339 ]
 [141.45836]]
66000 Cost:  0.40257663 
Prediction:
 [[151.07652]
 [184.84753]
 [180.55556]
 [196.73221]
 [141.45958]]
66100 Cost:  0.40160817 
Prediction:
 [[151.0775 ]
 [184.84708]
 [180.55612]
 [196.73048]
 [141.46077]]
66200 Cost:  0.40064788 
Prediction:
 [[151.07846]
 [184.84663]
 [180.55669]
 [196.72878]
 [141.46198]]
66300 Cost:  0.39969173 
Prediction:
 [[151.07942]
 [184.84616]
 [180.55724]
 [196.72707]
 [141.46317]]
66400 Cost:  0.39874157 
Prediction:
 [[151.0804 ]
 [184.84572]
 

73500 Cost:  0.34171468 
Prediction:
 [[151.14348]
 [184.81636]
 [180.59459]
 [196.61479]
 [141.54205]]
73600 Cost:  0.34105453 
Prediction:
 [[151.14429]
 [184.816  ]
 [180.59508]
 [196.61339]
 [141.54305]]
73700 Cost:  0.34037802 
Prediction:
 [[151.14511]
 [184.81561]
 [180.59555]
 [196.61195]
 [141.54405]]
73800 Cost:  0.3397084 
Prediction:
 [[151.14592]
 [184.81523]
 [180.59601]
 [196.61053]
 [141.54506]]
73900 Cost:  0.3390554 
Prediction:
 [[151.14673]
 [184.8149 ]
 [180.59651]
 [196.60915]
 [141.54607]]
74000 Cost:  0.3383924 
Prediction:
 [[151.14752]
 [184.81451]
 [180.59695]
 [196.60771]
 [141.54704]]
74100 Cost:  0.33773154 
Prediction:
 [[151.14833]
 [184.81412]
 [180.59741]
 [196.6063 ]
 [141.54803]]
74200 Cost:  0.33708218 
Prediction:
 [[151.14914]
 [184.81374]
 [180.59789]
 [196.6049 ]
 [141.54903]]
74300 Cost:  0.33643013 
Prediction:
 [[151.14993]
 [184.81337]
 [180.59834]
 [196.60349]
 [141.55   ]]
74400 Cost:  0.3357853 
Prediction:
 [[151.15074]
 [184.81302]
 [18

81600 Cost:  0.29662934 
Prediction:
 [[151.20335]
 [184.78851]
 [180.62947]
 [196.50986]
 [141.61583]]
81700 Cost:  0.29617152 
Prediction:
 [[151.20403]
 [184.78821]
 [180.62985]
 [196.50868]
 [141.61665]]
81800 Cost:  0.2957201 
Prediction:
 [[151.20471]
 [184.7879 ]
 [180.63025]
 [196.50754]
 [141.61748]]
81900 Cost:  0.2952655 
Prediction:
 [[151.20537]
 [184.7876 ]
 [180.63062]
 [196.50636]
 [141.6183 ]]
82000 Cost:  0.29481974 
Prediction:
 [[151.20602]
 [184.7873 ]
 [180.63101]
 [196.50519]
 [141.61913]]
82100 Cost:  0.2943817 
Prediction:
 [[151.20668]
 [184.78697]
 [180.63141]
 [196.50403]
 [141.61993]]
82200 Cost:  0.29393274 
Prediction:
 [[151.20735]
 [184.78668]
 [180.63177]
 [196.50288]
 [141.62074]]
82300 Cost:  0.293493 
Prediction:
 [[151.20801]
 [184.78636]
 [180.63216]
 [196.50172]
 [141.62155]]
82400 Cost:  0.2930544 
Prediction:
 [[151.20866]
 [184.78604]
 [180.63254]
 [196.50056]
 [141.62236]]
82500 Cost:  0.292619 
Prediction:
 [[151.20932]
 [184.78577]
 [180.63

90500 Cost:  0.26373935 
Prediction:
 [[151.25694]
 [184.7636 ]
 [180.66058]
 [196.41602]
 [141.68182]]
90600 Cost:  0.2634487 
Prediction:
 [[151.25749]
 [184.76332]
 [180.6609 ]
 [196.41508]
 [141.68248]]
90700 Cost:  0.26315585 
Prediction:
 [[151.25804]
 [184.76308]
 [180.66122]
 [196.41415]
 [141.68314]]
90800 Cost:  0.26286334 
Prediction:
 [[151.25858]
 [184.76285]
 [180.66153]
 [196.41324]
 [141.6838 ]]
90900 Cost:  0.26257533 
Prediction:
 [[151.25911]
 [184.76259]
 [180.66185]
 [196.4123 ]
 [141.68446]]
91000 Cost:  0.26228827 
Prediction:
 [[151.25964]
 [184.76236]
 [180.66217]
 [196.41138]
 [141.68513]]
91100 Cost:  0.26199812 
Prediction:
 [[151.26016]
 [184.7621 ]
 [180.66246]
 [196.41043]
 [141.68579]]
91200 Cost:  0.2617159 
Prediction:
 [[151.26068]
 [184.76186]
 [180.66278]
 [196.4095 ]
 [141.68646]]
91300 Cost:  0.2614252 
Prediction:
 [[151.26122]
 [184.76161]
 [180.66309]
 [196.40855]
 [141.68712]]
91400 Cost:  0.26114643 
Prediction:
 [[151.26173]
 [184.7614 ]
 [1

98500 Cost:  0.24413452 
Prediction:
 [[151.29622]
 [184.74532]
 [180.68335]
 [196.34743]
 [141.73013]]
98600 Cost:  0.24392538 
Prediction:
 [[151.29668]
 [184.74512]
 [180.6836 ]
 [196.34665]
 [141.73068]]
98700 Cost:  0.24372944 
Prediction:
 [[151.2971 ]
 [184.7449 ]
 [180.68385]
 [196.34587]
 [141.73125]]
98800 Cost:  0.24352765 
Prediction:
 [[151.29755]
 [184.7447 ]
 [180.68411]
 [196.34508]
 [141.7318 ]]
98900 Cost:  0.24332893 
Prediction:
 [[151.29799]
 [184.7445 ]
 [180.68437]
 [196.34431]
 [141.73236]]
99000 Cost:  0.24313577 
Prediction:
 [[151.29839]
 [184.7443 ]
 [180.6846 ]
 [196.34352]
 [141.7329 ]]
99100 Cost:  0.24293904 
Prediction:
 [[151.29883]
 [184.74413]
 [180.68488]
 [196.34276]
 [141.73346]]
99200 Cost:  0.24274194 
Prediction:
 [[151.29926]
 [184.7439 ]
 [180.6851 ]
 [196.34198]
 [141.734  ]]
99300 Cost:  0.24254675 
Prediction:
 [[151.2997 ]
 [184.7437 ]
 [180.68536]
 [196.34122]
 [141.73454]]
99400 Cost:  0.24234903 
Prediction:
 [[151.30013]
 [184.74348]
