## Multi-variable linear regression

In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = w1*x1_data + w2*x2_data + w3*x3_data + b

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()

In [7]:
sess.run(tf.global_variables_initializer())

In [9]:
for step in range(20001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],
                        feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 200 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  3.8373115 
Prediction:
 [154.19968 182.78542 181.55173 196.74336 139.4538 ]
200 Cost:  3.4623418 
Prediction:
 [154.05515 182.88458 181.5075  196.71085 139.58438]
400 Cost:  3.125893 
Prediction:
 [153.91821 182.97847 181.4656  196.68    139.70807]
600 Cost:  2.8239713 
Prediction:
 [153.78854 183.06744 181.42595 196.65076 139.82529]
800 Cost:  2.5530834 
Prediction:
 [153.66571 183.15169 181.38837 196.62305 139.93631]
1000 Cost:  2.3100202 
Prediction:
 [153.54938 183.2315  181.35278 196.5968  140.04149]
1200 Cost:  2.0919137 
Prediction:
 [153.43918 183.3071  181.31909 196.5719  140.14114]
1400 Cost:  1.8962376 
Prediction:
 [153.33484 183.3787  181.28717 196.54828 140.23553]
1600 Cost:  1.7206329 
Prediction:
 [153.236   183.4465  181.25693 196.52591 140.32498]
1800 Cost:  1.5630906 
Prediction:
 [153.14238 183.51074 181.22833 196.5047  140.40971]
2000 Cost:  1.421713 
Prediction:
 [153.05371 183.57156 181.2012  196.48457 140.48999]
2200 Cost:  1.2948639 
Prediction:
 [152.

19400 Cost:  0.1854971 
Prediction:
 [151.48819 184.64839 180.7255  196.10559 141.93355]
19600 Cost:  0.18547255 
Prediction:
 [151.48758 184.64885 180.72534 196.10516 141.93442]
19800 Cost:  0.18545102 
Prediction:
 [151.48698 184.64926 180.72519 196.1047  141.93527]
20000 Cost:  0.18543264 
Prediction:
 [151.48645 184.64966 180.72507 196.10431 141.93607]
