## Logistic(regression) classifier

In [1]:
import tensorflow as tf

In [2]:
x_data = [[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data = [[0],[0],[0],[1],[1],[1]]

In [3]:
X = tf.placeholder(tf.float32, shape = [None,2])
Y = tf.placeholder(tf.float32, shape = [None,1])

In [4]:
W = tf.Variable(tf.random_normal([2,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [5]:
hypothesis = tf.sigmoid(tf.matmul(X,W) + b)

In [6]:
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1 - Y) * tf.log(1-hypothesis))

In [7]:
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

In [8]:
# tf.cast : 조건에 맞으면 1, 틀리면 0으로 변환됨
predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted,Y), dtype = tf.float32))

In [11]:
# with tf.Session() as sess:
#     sess.run(tf.global_variables_initializer())
    
#     for step in range(10001):
#         cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
#                             feed_dict={X:x_data, Y:y_data})
#         if step % 200 == 0:
#             print('step:',step,'/cost:',cost_val,'\nprediction:\n', hy_val)

step: 0 /cost: 0.7689505 
prediction:
 [[0.18280765]
 [0.20393988]
 [0.22036476]
 [0.24684253]
 [0.27044603]
 [0.29284102]]
step: 200 /cost: 0.37810138 
prediction:
 [[0.25266063]
 [0.39031726]
 [0.5252726 ]
 [0.683546  ]
 [0.7986959 ]
 [0.8760739 ]]
step: 400 /cost: 0.3520328 
prediction:
 [[0.20650926]
 [0.33227825]
 [0.5428619 ]
 [0.67835236]
 [0.81279343]
 [0.9058664 ]]
step: 600 /cost: 0.33479774 
prediction:
 [[0.17651527]
 [0.29513344]
 [0.5510675 ]
 [0.676822  ]
 [0.8240597 ]
 [0.92303574]]
step: 800 /cost: 0.32170284 
prediction:
 [[0.15556435]
 [0.27013177]
 [0.5532671 ]
 [0.67731833]
 [0.83329886]
 [0.93382365]]
step: 1000 /cost: 0.31079724 
prediction:
 [[0.14006534]
 [0.25256786]
 [0.5515007 ]
 [0.67900753]
 [0.84108233]
 [0.94107175]]
step: 1200 /cost: 0.30118898 
prediction:
 [[0.12806198]
 [0.23978662]
 [0.54706967]
 [0.6814437 ]
 [0.84781253]
 [0.94621396]]
step: 1400 /cost: 0.29243746 
prediction:
 [[0.11841316]
 [0.23020117]
 [0.5408337 ]
 [0.6843636 ]
 [0.8537643 ]


In [15]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(10001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                        feed_dict={X:x_data, Y:y_data})
    if step % 200 == 0:
        print('step:',step,'/cost:',cost_val,'\nprediction:\n', hy_val)

step: 0 /cost: 4.277661 
prediction:
 [[4.4980042e-02]
 [6.8550687e-03]
 [7.2863731e-03]
 [5.5531447e-04]
 [1.5761681e-04]
 [8.6581014e-05]]
step: 200 /cost: 0.5273773 
prediction:
 [[0.42607105]
 [0.4808628 ]
 [0.6296483 ]
 [0.65098256]
 [0.7257837 ]
 [0.81030124]]
step: 400 /cost: 0.47255817 
prediction:
 [[0.3332753 ]
 [0.38400432]
 [0.656072  ]
 [0.63817686]
 [0.7479074 ]
 [0.8706487 ]]
step: 600 /cost: 0.4412789 
prediction:
 [[0.27586854]
 [0.3269058 ]
 [0.6681653 ]
 [0.63405246]
 [0.76594764]
 [0.9015519 ]]
step: 800 /cost: 0.41958377 
prediction:
 [[0.23770003]
 [0.2913004 ]
 [0.6715898 ]
 [0.633881  ]
 [0.78038174]
 [0.9190581 ]]
step: 1000 /cost: 0.40239492 
prediction:
 [[0.21060355]
 [0.2678747 ]
 [0.6695396 ]
 [0.63569707]
 [0.79213136]
 [0.9298333 ]]
step: 1200 /cost: 0.3876358 
prediction:
 [[0.19030604]
 [0.2517941 ]
 [0.6639131 ]
 [0.63863415]
 [0.8019766 ]
 [0.936923  ]]
step: 1400 /cost: 0.37437057 
prediction:
 [[0.1744179 ]
 [0.24037349]
 [0.6558925 ]
 [0.64225227]

In [16]:
h,c,a = sess.run([hypothesis, predicted, accuracy],
                 feed_dict={X:x_data, Y:y_data})
print('\nHypothesis:', h, '\nCorrect(Y):',c,'\nAccuracy:',a)


Hypothesis: [[0.02906338]
 [0.15651031]
 [0.29674032]
 [0.78511953]
 [0.9419061 ]
 [0.98095393]] 
Correct(Y): [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 1.0
