## Loading Data from File

In [14]:
import tensorflow as tf
import numpy as np

In [15]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [16]:
x_data

array([[ 73.,  80.,  75.],
       [ 93.,  88.,  93.],
       [ 89.,  91.,  90.],
       [ 96.,  98., 100.],
       [ 73.,  66.,  70.],
       [ 53.,  46.,  55.],
       [ 69.,  74.,  77.],
       [ 47.,  56.,  60.],
       [ 87.,  79.,  90.],
       [ 79.,  70.,  88.],
       [ 69.,  70.,  73.],
       [ 70.,  65.,  74.],
       [ 93.,  95.,  91.],
       [ 79.,  80.,  73.],
       [ 70.,  73.,  78.],
       [ 93.,  89.,  96.],
       [ 78.,  75.,  68.],
       [ 81.,  90.,  93.],
       [ 88.,  92.,  86.],
       [ 78.,  83.,  77.],
       [ 82.,  86.,  90.],
       [ 86.,  82.,  89.],
       [ 78.,  83.,  85.],
       [ 76.,  83.,  71.],
       [ 96.,  93.,  95.]], dtype=float32)

In [17]:
y_data

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.],
       [101.],
       [149.],
       [115.],
       [175.],
       [164.],
       [141.],
       [141.],
       [184.],
       [152.],
       [148.],
       [192.],
       [147.],
       [183.],
       [177.],
       [159.],
       [177.],
       [175.],
       [175.],
       [149.],
       [192.]], dtype=float32)

In [18]:
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [19]:
W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bais')

In [21]:
hypothesis = tf.matmul(X,W) + b

In [22]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [23]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)

In [24]:
train = optimizer.minimize(cost)

In [25]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [29]:
# 100,000번 학습
for i in range(100000):
    cost_val, hy_val, _ = sess.run([cost,hypothesis,train],
                        feed_dict={X:x_data, Y:y_data})
    if i % 1000 == 0:
        print(i, "Cost: ", cost_val, '\nPrediction:\n', hy_val)

0 Cost:  6.0202336 
Prediction:
 [[152.90576 ]
 [184.65297 ]
 [181.42856 ]
 [198.96082 ]
 [139.80273 ]
 [105.06986 ]
 [150.55441 ]
 [113.909355]
 [174.33551 ]
 [164.43759 ]
 [143.9005  ]
 [142.72964 ]
 [186.11166 ]
 [152.77887 ]
 [151.51051 ]
 [188.57993 ]
 [144.10538 ]
 [181.44325 ]
 [177.07724 ]
 [158.54495 ]
 [176.27718 ]
 [174.44287 ]
 [167.59886 ]
 [151.04231 ]
 [190.64343 ]]
1000 Cost:  6.020018 
Prediction:
 [[152.90567]
 [184.6531 ]
 [181.42871]
 [198.96114]
 [139.80244]
 [105.06932]
 [150.55432]
 [113.90899]
 [174.33557]
 [164.43759]
 [143.90031]
 [142.72945]
 [186.11182]
 [152.77872]
 [151.51044]
 [188.58012]
 [144.1051 ]
 [181.44348]
 [177.07733]
 [158.54488]
 [176.27731]
 [174.44296]
 [167.59892]
 [151.04214]
 [190.64365]]
2000 Cost:  6.0198073 
Prediction:
 [[152.90556 ]
 [184.65326 ]
 [181.42883 ]
 [198.96146 ]
 [139.80219 ]
 [105.06876 ]
 [150.55423 ]
 [113.908585]
 [174.33563 ]
 [164.4376  ]
 [143.90013 ]
 [142.72925 ]
 [186.11198 ]
 [152.77856 ]
 [151.51033 ]
 [188.580

22000 Cost:  6.015412 
Prediction:
 [[152.90343]
 [184.65645]
 [181.43166]
 [198.96759]
 [139.79712]
 [105.05783]
 [150.55205]
 [113.90028]
 [174.33714]
 [164.43773]
 [143.89642]
 [142.7252 ]
 [186.11543]
 [152.77574]
 [151.5083 ]
 [188.58444]
 [144.10016]
 [181.44737]
 [177.07927]
 [158.54344]
 [176.27986]
 [174.44463]
 [167.59978]
 [151.03906]
 [190.64806]]
23000 Cost:  6.0151906 
Prediction:
 [[152.9033  ]
 [184.6566  ]
 [181.43178 ]
 [198.96788 ]
 [139.79684 ]
 [105.05729 ]
 [150.55193 ]
 [113.899864]
 [174.3372  ]
 [164.43773 ]
 [143.89622 ]
 [142.72499 ]
 [186.11557 ]
 [152.77559 ]
 [151.50818 ]
 [188.58464 ]
 [144.0999  ]
 [181.44753 ]
 [177.07936 ]
 [158.54337 ]
 [176.27995 ]
 [174.44469 ]
 [167.59981 ]
 [151.0389  ]
 [190.64827 ]]
24000 Cost:  6.0149746 
Prediction:
 [[152.9032  ]
 [184.65678 ]
 [181.43193 ]
 [198.9682  ]
 [139.79662 ]
 [105.056755]
 [150.55183 ]
 [113.89945 ]
 [174.33731 ]
 [164.43776 ]
 [143.89606 ]
 [142.72482 ]
 [186.11575 ]
 [152.77547 ]
 [151.50809 ]
 [1

45000 Cost:  6.0105867 
Prediction:
 [[152.90085]
 [184.66013]
 [181.43471]
 [198.9744 ]
 [139.79164]
 [105.04591]
 [150.54956]
 [113.89091]
 [174.33907]
 [164.43823]
 [143.8923 ]
 [142.72092]
 [186.11914]
 [152.77252]
 [151.50601]
 [188.58916]
 [144.09488]
 [181.45131]
 [177.08118]
 [158.54175]
 [176.28247]
 [174.44653]
 [167.60059]
 [151.03549]
 [190.65283]]
46000 Cost:  6.0103846 
Prediction:
 [[152.90074 ]
 [184.6603  ]
 [181.43483 ]
 [198.97469 ]
 [139.79141 ]
 [105.04539 ]
 [150.54945 ]
 [113.890495]
 [174.33916 ]
 [164.43825 ]
 [143.89212 ]
 [142.72073 ]
 [186.11931 ]
 [152.77238 ]
 [151.5059  ]
 [188.58937 ]
 [144.09465 ]
 [181.45148 ]
 [177.08127 ]
 [158.54167 ]
 [176.28258 ]
 [174.44661 ]
 [167.6006  ]
 [151.03535 ]
 [190.65303 ]]
47000 Cost:  6.0101705 
Prediction:
 [[152.90063 ]
 [184.66046 ]
 [181.43498 ]
 [198.97499 ]
 [139.79118 ]
 [105.044876]
 [150.54933 ]
 [113.89009 ]
 [174.33923 ]
 [164.43826 ]
 [143.89195 ]
 [142.72054 ]
 [186.11946 ]
 [152.77223 ]
 [151.50581 ]
 [

67000 Cost:  6.006033 
Prediction:
 [[152.89839 ]
 [184.66365 ]
 [181.4376  ]
 [198.98083 ]
 [139.7865  ]
 [105.0346  ]
 [150.54715 ]
 [113.881935]
 [174.34091 ]
 [164.43869 ]
 [143.88837 ]
 [142.71684 ]
 [186.1227  ]
 [152.76947 ]
 [151.50381 ]
 [188.59364 ]
 [144.08994 ]
 [181.455   ]
 [177.08301 ]
 [158.54013 ]
 [176.28493 ]
 [174.44835 ]
 [167.60132 ]
 [151.03214 ]
 [190.65738 ]]
68000 Cost:  6.005825 
Prediction:
 [[152.89828]
 [184.66382]
 [181.43774]
 [198.98114]
 [139.78625]
 [105.03407]
 [150.54704]
 [113.88152]
 [174.341  ]
 [164.4387 ]
 [143.88818]
 [142.71664]
 [186.12286]
 [152.76933]
 [151.50371]
 [188.59384]
 [144.08972]
 [181.45517]
 [177.0831 ]
 [158.54007]
 [176.28503]
 [174.44843]
 [167.60135]
 [151.03198]
 [190.6576 ]]
69000 Cost:  6.005628 
Prediction:
 [[152.89816]
 [184.66397]
 [181.43787]
 [198.98143]
 [139.78601]
 [105.03358]
 [150.54694]
 [113.88113]
 [174.34108]
 [164.43872]
 [143.88802]
 [142.71646]
 [186.12302]
 [152.7692 ]
 [151.5036 ]
 [188.59406]
 [144.0

90000 Cost:  6.0013304 
Prediction:
 [[152.89583]
 [184.66733]
 [181.44064]
 [198.98758]
 [139.7811 ]
 [105.02276]
 [150.54465]
 [113.87255]
 [174.34283]
 [164.43916]
 [143.88428]
 [142.71259]
 [186.1264 ]
 [152.7663 ]
 [151.50151]
 [188.59833]
 [144.08476]
 [181.45886]
 [177.08492]
 [158.53845]
 [176.2875 ]
 [174.45023]
 [167.60208]
 [151.02863]
 [190.66211]]
91000 Cost:  6.001131 
Prediction:
 [[152.89572 ]
 [184.66748 ]
 [181.44078 ]
 [198.98788 ]
 [139.78087 ]
 [105.022255]
 [150.54453 ]
 [113.87216 ]
 [174.34293 ]
 [164.4392  ]
 [143.8841  ]
 [142.7124  ]
 [186.12659 ]
 [152.76616 ]
 [151.50142 ]
 [188.59854 ]
 [144.08453 ]
 [181.45905 ]
 [177.08499 ]
 [158.53839 ]
 [176.28763 ]
 [174.45032 ]
 [167.60211 ]
 [151.02847 ]
 [190.66232 ]]
92000 Cost:  6.000927 
Prediction:
 [[152.89561 ]
 [184.66765 ]
 [181.44092 ]
 [198.98817 ]
 [139.78064 ]
 [105.021736]
 [150.54443 ]
 [113.87175 ]
 [174.343   ]
 [164.43921 ]
 [143.88391 ]
 [142.71222 ]
 [186.12674 ]
 [152.76602 ]
 [151.50131 ]
 [18

In [30]:
# 내 점수 예측
print("Your score will be ", sess.run(hypothesis,
                            feed_dict={X:[[100,70,101]]}))

Your score will be  [[186.64676]]
