## Example - Classifying Diabetes 

In [2]:
import tensorflow as tf
import numpy as np

### Load Data

In [3]:
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
xy

array([[-0.294118 ,  0.487437 ,  0.180328 , ..., -0.53117  , -0.0333333,
         0.       ],
       [-0.882353 , -0.145729 ,  0.0819672, ..., -0.766866 , -0.666667 ,
         1.       ],
       [-0.0588235,  0.839196 ,  0.0491803, ..., -0.492741 , -0.633333 ,
         0.       ],
       ...,
       [-0.411765 ,  0.21608  ,  0.180328 , ..., -0.857387 , -0.7      ,
         1.       ],
       [-0.882353 ,  0.266332 , -0.0163934, ..., -0.768574 , -0.133333 ,
         0.       ],
       [-0.882353 , -0.0653266,  0.147541 , ..., -0.797609 , -0.933333 ,
         1.       ]], dtype=float32)

### Slice Data X and Y

In [4]:
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [5]:
x_data

array([[-0.294118  ,  0.487437  ,  0.180328  , ...,  0.00149028,
        -0.53117   , -0.0333333 ],
       [-0.882353  , -0.145729  ,  0.0819672 , ..., -0.207153  ,
        -0.766866  , -0.666667  ],
       [-0.0588235 ,  0.839196  ,  0.0491803 , ..., -0.305514  ,
        -0.492741  , -0.633333  ],
       ...,
       [-0.411765  ,  0.21608   ,  0.180328  , ..., -0.219076  ,
        -0.857387  , -0.7       ],
       [-0.882353  ,  0.266332  , -0.0163934 , ..., -0.102832  ,
        -0.768574  , -0.133333  ],
       [-0.882353  , -0.0653266 ,  0.147541  , ..., -0.0938897 ,
        -0.797609  , -0.933333  ]], dtype=float32)

In [6]:
y_data

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],

In [7]:
X = tf.placeholder(tf.float32, shape=[None,8])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [8]:
W = tf.Variable(tf.random_normal([8,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [10]:
# sigmoid 함수에 W*X+b 값을 넣어줌 --> 결과값 : 0 ~ 1 값
hypothesis = tf.sigmoid(tf.matmul(X,W) + b)

In [11]:
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

In [12]:
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [13]:
predicted = tf.cast(hypothesis>0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(Y,predicted), dtype = tf.float32))

In [22]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(70000):
        cost_val,_,acc = sess.run([cost, train, accuracy],
                    feed_dict={X:x_data, Y:y_data})
        if step % 100 == 0:
            print('step:',step,'\ncost:',cost_val,'\nAccuracy:',acc)
            
#     h,p,a = sess.run([hypothesis, predicted, accuracy],
#             feed_dict={X:x_data, Y:y_data})
#     print('Accuracy:',a)

step: 0 
cost: 2.1342833 
Accuracy: 0.342556
step: 100 
cost: 1.4326553 
Accuracy: 0.34123847
step: 200 
cost: 1.0233072 
Accuracy: 0.33596838
step: 300 
cost: 0.8434038 
Accuracy: 0.46113306
step: 400 
cost: 0.76913506 
Accuracy: 0.5362319
step: 500 
cost: 0.73500925 
Accuracy: 0.5704875
step: 600 
cost: 0.71612346 
Accuracy: 0.5836627
step: 700 
cost: 0.7033481 
Accuracy: 0.5928854
step: 800 
cost: 0.69321215 
Accuracy: 0.60474306
step: 900 
cost: 0.68433887 
Accuracy: 0.61528325
step: 1000 
cost: 0.67616284 
Accuracy: 0.62582344
step: 1100 
cost: 0.6684441 
Accuracy: 0.63109356
step: 1200 
cost: 0.66107756 
Accuracy: 0.63109356
step: 1300 
cost: 0.6540147 
Accuracy: 0.6350461
step: 1400 
cost: 0.64723086 
Accuracy: 0.63241106
step: 1500 
cost: 0.6407113 
Accuracy: 0.6350461
step: 1600 
cost: 0.6344457 
Accuracy: 0.63372856
step: 1700 
cost: 0.62842554 
Accuracy: 0.6403162
step: 1800 
cost: 0.62264305 
Accuracy: 0.6469038
step: 1900 
cost: 0.6170906 
Accuracy: 0.6495389
step: 2000 
c

Accuracy: 0.76811594
step: 16900 
cost: 0.47616562 
Accuracy: 0.76811594
step: 17000 
cost: 0.4761026 
Accuracy: 0.76943344
step: 17100 
cost: 0.47604084 
Accuracy: 0.76943344
step: 17200 
cost: 0.47598034 
Accuracy: 0.76943344
step: 17300 
cost: 0.47592083 
Accuracy: 0.76943344
step: 17400 
cost: 0.4758624 
Accuracy: 0.76943344
step: 17500 
cost: 0.4758051 
Accuracy: 0.76943344
step: 17600 
cost: 0.4757488 
Accuracy: 0.76943344
step: 17700 
cost: 0.4756936 
Accuracy: 0.76943344
step: 17800 
cost: 0.47563937 
Accuracy: 0.76943344
step: 17900 
cost: 0.47558618 
Accuracy: 0.76943344
step: 18000 
cost: 0.47553387 
Accuracy: 0.76943344
step: 18100 
cost: 0.47548243 
Accuracy: 0.76943344
step: 18200 
cost: 0.475432 
Accuracy: 0.76943344
step: 18300 
cost: 0.47538254 
Accuracy: 0.76943344
step: 18400 
cost: 0.47533384 
Accuracy: 0.76943344
step: 18500 
cost: 0.47528604 
Accuracy: 0.76943344
step: 18600 
cost: 0.4752391 
Accuracy: 0.76943344
step: 18700 
cost: 0.4751929 
Accuracy: 0.76943344


step: 33300 
cost: 0.47246358 
Accuracy: 0.76943344
step: 33400 
cost: 0.4724569 
Accuracy: 0.76943344
step: 33500 
cost: 0.47245023 
Accuracy: 0.76943344
step: 33600 
cost: 0.47244367 
Accuracy: 0.76943344
step: 33700 
cost: 0.47243708 
Accuracy: 0.76943344
step: 33800 
cost: 0.47243056 
Accuracy: 0.76943344
step: 33900 
cost: 0.4724242 
Accuracy: 0.76943344
step: 34000 
cost: 0.47241777 
Accuracy: 0.76943344
step: 34100 
cost: 0.47241154 
Accuracy: 0.76943344
step: 34200 
cost: 0.4724053 
Accuracy: 0.76943344
step: 34300 
cost: 0.47239918 
Accuracy: 0.76943344
step: 34400 
cost: 0.4723931 
Accuracy: 0.76943344
step: 34500 
cost: 0.47238702 
Accuracy: 0.76943344
step: 34600 
cost: 0.47238103 
Accuracy: 0.76943344
step: 34700 
cost: 0.47237515 
Accuracy: 0.76943344
step: 34800 
cost: 0.47236925 
Accuracy: 0.76943344
step: 34900 
cost: 0.4723635 
Accuracy: 0.76943344
step: 35000 
cost: 0.47235763 
Accuracy: 0.76943344
step: 35100 
cost: 0.47235188 
Accuracy: 0.76943344
step: 35200 
cost

step: 49800 
cost: 0.47188568 
Accuracy: 0.76811594
step: 49900 
cost: 0.471884 
Accuracy: 0.76811594
step: 50000 
cost: 0.4718824 
Accuracy: 0.76811594
step: 50100 
cost: 0.47188085 
Accuracy: 0.76811594
step: 50200 
cost: 0.4718793 
Accuracy: 0.76811594
step: 50300 
cost: 0.47187772 
Accuracy: 0.76811594
step: 50400 
cost: 0.47187617 
Accuracy: 0.76811594
step: 50500 
cost: 0.47187462 
Accuracy: 0.76811594
step: 50600 
cost: 0.47187313 
Accuracy: 0.76811594
step: 50700 
cost: 0.47187155 
Accuracy: 0.76811594
step: 50800 
cost: 0.47187006 
Accuracy: 0.76811594
step: 50900 
cost: 0.47186857 
Accuracy: 0.76811594
step: 51000 
cost: 0.47186714 
Accuracy: 0.76811594
step: 51100 
cost: 0.4718656 
Accuracy: 0.76811594
step: 51200 
cost: 0.4718642 
Accuracy: 0.76811594
step: 51300 
cost: 0.4718627 
Accuracy: 0.76811594
step: 51400 
cost: 0.47186133 
Accuracy: 0.76811594
step: 51500 
cost: 0.47185987 
Accuracy: 0.76811594
step: 51600 
cost: 0.4718585 
Accuracy: 0.76811594
step: 51700 
cost: 0

step: 66400 
cost: 0.47173366 
Accuracy: 0.76811594
step: 66500 
cost: 0.47173327 
Accuracy: 0.76811594
step: 66600 
cost: 0.4717328 
Accuracy: 0.76811594
step: 66700 
cost: 0.47173235 
Accuracy: 0.76811594
step: 66800 
cost: 0.47173184 
Accuracy: 0.76811594
step: 66900 
cost: 0.4717314 
Accuracy: 0.76811594
step: 67000 
cost: 0.471731 
Accuracy: 0.76811594
step: 67100 
cost: 0.4717305 
Accuracy: 0.76811594
step: 67200 
cost: 0.47173014 
Accuracy: 0.76811594
step: 67300 
cost: 0.4717297 
Accuracy: 0.76811594
step: 67400 
cost: 0.47172925 
Accuracy: 0.76811594
step: 67500 
cost: 0.47172886 
Accuracy: 0.76811594
step: 67600 
cost: 0.4717284 
Accuracy: 0.76811594
step: 67700 
cost: 0.47172803 
Accuracy: 0.76811594
step: 67800 
cost: 0.47172752 
Accuracy: 0.76811594
step: 67900 
cost: 0.47172722 
Accuracy: 0.76811594
step: 68000 
cost: 0.47172678 
Accuracy: 0.76811594
step: 68100 
cost: 0.47172633 
Accuracy: 0.76811594
step: 68200 
cost: 0.471726 
Accuracy: 0.76811594
step: 68300 
cost: 0.