## Multi Value Classification

In [1]:
import tensorflow as tf

In [3]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],
          [1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [4]:
X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,3])

In [5]:
nb_classes = 3

In [6]:
W = tf.Variable(tf.random_normal([4,nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bais')

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)

In [9]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [13]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for i in range(2001):
    sess.run(train, feed_dict={X:x_data, Y:y_data})
    if i % 200 == 0:
        print(i, sess.run(cost, feed_dict={X:x_data, Y:y_data}))

0 6.202754
200 0.59471345
400 0.49475545
600 0.41834646
800 0.34911323
1000 0.27871054
1200 0.22890761
1400 0.20818475
1600 0.19075063
1800 0.17589606
2000 0.16310154


In [14]:
a = sess.run(hypothesis, feed_dict={X:[[1,11,7,9]]})

In [16]:
print(a, sess.run(tf.arg_max(a,1)))

W0707 14:18:25.510317  8344 deprecation.py:323] From <ipython-input-16-831bc8a88aa5>:1: arg_max (from tensorflow.python.ops.gen_math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.math.argmax` instead


[[1.2197922e-02 9.8779196e-01 1.0091747e-05]] [1]


In [17]:
all = sess.run(hypothesis, feed_dict={X:[[1,11,7,9],
                                         [1,3,4,3],
                                        [1,1,0,1]]})
print(all, sess.run(tf.argmax(all,1)))

[[1.2197898e-02 9.8779196e-01 1.0091728e-05]
 [7.9353422e-01 1.8572749e-01 2.0738347e-02]
 [2.1014905e-08 3.8327969e-04 9.9961662e-01]] [1 0 2]
